---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: argo-cd
          releaseName: argocd
        selector:
          matchExpressions:
            - key: enable_argocd
              operator: In
              values: ['true']
  template:
    metadata:
      name: addon-{{.values.releaseName}}
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.addons_repo_url}}'
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: https://argoproj.github.io/argo-helm
          targetRevision: 7.9.1
          helm:
            releaseName: '{{.values.releaseName}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/default/{{.values.releaseName}}/values.yaml
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/{{.metadata.labels.environment}}/{{.values.releaseName}}/values.yaml
      destination:
        name: '{{.name}}'
        namespace: '{{.values.releaseName}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs
