---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-aws-load-balancer-controller
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: aws-load-balancer-controller
        selector:
          matchExpressions:
            - key: enable_aws_load_balancer_controller
              operator: In
              values: ['true']
  template:
    metadata:
      name: addon-{{.values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.addons_repo_url}}'
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: https://aws.github.io/eks-charts
          targetRevision: 1.8.2
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/default/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/{{.metadata.labels.environment}}/{{.values.addonChart}}/values.yaml
            valuesObject:
              vpcId: '{{.metadata.annotations.aws_vpc_id}}'
              clusterName: '{{.metadata.annotations.aws_cluster_name}}'
              serviceAccount:
                name: '{{.metadata.annotations.aws_load_balancer_controller_service_account}}'
                annotations:
                  eks.amazonaws.com/role-arn: '{{.metadata.annotations.aws_load_balancer_controller_iam_role_arn}}'
      destination:
        name: '{{.name}}'
        namespace: '{{.metadata.annotations.aws_load_balancer_controller_namespace}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs
      ignoreDifferences:
        - kind: Secret
          name: aws-load-balancer-tls
          jsonPointers: [/data]
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions: ['.webhooks[].clientConfig.caBundle']
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions: ['.webhooks[].clientConfig.caBundle']
