---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: cert-manager
        selector:
          matchExpressions:
            - key: enable_cert_manager
              operator: In
              values: ['true']
  template:
    metadata:
      name: '{{values.addonChart}}'
    spec:
      project: default
      sources:
        # - repoURL: '{{metadata.annotations.addons_repo_url}}'
        #   targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        #   ref: values
        - chart: cert-manager
          repoURL: https://charts.jetstack.io
          targetRevision: v1.14.3
          helm:
            releaseName: cert-manager
            ignoreMissingValueFiles: true
            valueFiles:
              - '{{metadata.annotations.addons_repo_basepath}}environments/default/{{values.addonChart}}/values.yaml'
              - '{{metadata.annotations.addons_repo_basepath}}environments/{{metadata.labels.environment}}/{{values.addonChart}}/values.yaml'
            values: |
              installCRDs: true
              serviceAccount:
                name: {{metadata.annotations.cert_manager_service_account}}
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.cert_manager_iam_role_arn}}
      destination:
        namespace: '{{metadata.annotations.cert_manager_namespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
