---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-external-dns
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: external-dns
        selector:
          matchExpressions:
            - key: enable_external_dns
              operator: In
              values: ['true']
  template:
    metadata:
      name: addon-{{.values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.addons_repo_url}}'
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: https://kubernetes-sigs.github.io/external-dns
          targetRevision: 1.17.0
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/default/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/{{.metadata.labels.environment}}/{{.values.addonChart}}/values.yaml
            valuesObject:
              # serviceAccount:
              #   name: '{{.metadata.annotations.external_dns_service_account}}'
              #   annotations:
              #     eks.amazonaws.com/role-arn: '{{.metadata.annotations.external_dns_iam_role_arn}}'
              txtOwnerId: '{{.metadata.annotations.aws_cluster_name}}'
        - chart: k8s-resources
          repoURL: https://raw.githubusercontent.com/deliveryhero/helm-charts/refs/heads/master
          # chart: hello-world
          # repoURL: https://helm.github.io/examples
          targetRevision: 0.8.1
          helm:
            ignoreMissingValueFiles: true
            # valueFiles:
            #   - $values/{{.metadata.annotations.addons_repo_basepath}}environments/default/{{.values.addonChart}}/resources.yaml
            #   - $values/{{.metadata.annotations.addons_repo_basepath}}environments/{{.metadata.labels.environment}}/{{.values.addonChart}}/resources.yaml
            valuesObject:
              Secrets:
                - name: cloudflare-api-token
                  keys:
                    # token: '{{.metadata.annotations.cloudflare_api_token}}'
                    token: ZFpzalpKV1hWbUVQcGFmbjFTd3YwM0pHX09zdWFJUXpPWTVobDFWdQ==
      destination:
        name: '{{.name}}'
        namespace: '{{.metadata.annotations.external_dns_namespace}}'
      syncPolicy:
        # automated:
        #   prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs
