---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-cert-manager
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: cert-manager
        selector:
          matchExpressions:
            - key: enable_cert_manager
              operator: In
              values: ['true']
  template:
    metadata:
      name: addon-{{.values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.addons_repo_url}}'
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: https://charts.jetstack.io
          targetRevision: v1.16.4
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/default/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/{{.metadata.labels.environment}}/{{.values.addonChart}}/values.yaml
            valuesObject:
              serviceAccount:
                name: '{{.metadata.annotations.cert_manager_service_account}}'
                annotations:
                  eks.amazonaws.com/role-arn: '{{.metadata.annotations.cert_manager_iam_role_arn}}'
      destination:
        name: '{{.name}}'
        namespace: '{{.metadata.annotations.cert_manager_namespace}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs
