provider:
  name: cloudflare
domainFilters:
  - quentrix.com
policy: sync

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: token

serviceMonitor:
  enabled: false
  namespace: monitoring

txtPrefix: xdns-
extraArgs:
  - --txt-new-format-only  # keep registry "clean". No valid starting from version 0.18.0
